###GET Peron By ID
GET http://localhost:7000/api/person/1

###POST new
POST http://localhost:7000/api/person
Content-Type: application/json

{
  "name": "Victor"
}

###GET ALL
GET http://localhost:7000/api/persons


###PUT
PUT http://localhost:7000/api/person/2
Content-Type: application/json

{
  "name": "Tim"
}


###DELETE
DELETE http://localhost:7000/api/person/1

